# AGENTS.md - 0xinsider-rust

Instructions for AI coding agents working in this repository. This is the official Rust client for the 0xinsider Developer API.

0xinsider is Polymarket analytics for sports and esports in real-time: large
trades, wallet grades, sharp-money flow, positions, and research.

## Install

```
cargo add oxinsider
```

## Read before writing integration code

The canonical agent rules live in the official Agent Plugin:
<https://github.com/0xinsider/agent-plugin/blob/main/AGENTS.md>. Install the
whole plugin, including five skills covering API access, large trades, wallet
grades, sharp-money flow, and market research:

```bash
npx skills add 0xinsider/agent-plugin
```

## Rules that apply here

- **Use the sandbox first.** `https://0xinsider.com/sandbox` answers every
  documented operation with no credential and no production data
  (`Client::sandbox()`). Add `?sandbox_status=<code>` to exercise an error path.
- **Read credentials from the environment** (`OXINSIDER_API_KEY`,
  `Client::from_env()`). Never write a key into a config file, a committed
  script, or an example.
- **The OpenAPI spec is the source of truth.** This client is generated from
  <https://0xinsider.com/api/v1/openapi.json>. Regenerate rather than hand-edit
  generated files.
- **Batch instead of looping.** Batch reads accept 25 items against a
  100-request-per-minute budget.
- **Branch on `error.code`, never the message string.** In this crate:
  `ApiError::code` and `ApiError::reason`.
- **Follow cursors to completion.** Feeds and timelines are paged and move
  while you read them. Never page by offset, never total a partial page. Use
  `pagination::Pager`.
- **Send `Idempotency-Key` on writes,** and reuse it across retries.

## Rules for presenting the data

These are correctness requirements. Getting them wrong produces a confident,
wrong number.

- An absent field is not a zero. Serve a truthful unavailable state. In this
  crate an absent field is `None`; never `unwrap_or(0.0)` it for display.
- `pnl.realized` is omitted when no native accounting snapshot matches. Raw
  total P&L is never a substitute for it.
- The 0.0-1.0 significance score ranks attention, not outcomes. It is a
  different quantity from Insider Radar's 0-100 suspicion score. Neither is a
  probability or a forecast.
- `BUY YES` and `SELL NO` add exposure; `BUY NO` and `SELL YES` subtract it.
  A zero-flow YES tie-break is not conviction.
- An ungraded wallet is uncovered, not unskilled.
- Keep full numeric precision until the final render.
- Every polymarket.com link carries `?r=0xinsidercom`.

## Conventions

- No emojis, in code, docs, commits, or issues. Use plain-text markers.
- Before committing: `cargo fmt --check`, `cargo clippy --all-targets -- -D warnings`, `cargo test`, and `python3 scripts/generate.py --check`. `OXINSIDER_SANDBOX_TESTS=1 cargo test --test sandbox` checks the live sandbox.
- `src/models.rs`, `src/operations.rs`, `src/provenance.rs`, `tests/support/generated.rs` and `openapi.json` are generated by `scripts/generate.py` (Python 3 standard library, then `rustfmt`). Regenerate them rather than editing them; to change their shape, change the generator. The generator raises on a schema construct it does not understand; teach it the construct rather than emitting `serde_json::Value`.
- Everything else under `src/` is hand-written and owned outside the generated files: `client.rs` (configuration, retries, error decoding), `policy.rs` (where a credential may go), `stream.rs` (SSE), `pagination.rs`, `download.rs`, `webhooks.rs`, `error.rs`. See `ARCHITECTURE.md`.
- A bearer credential goes over `https://` only, or `http://` to a loopback host: `policy.rs` owns that check, `ClientBuilder::build` and every credentialed request run it, the default HTTP client follows no redirects, and `Download` fetches the redirect target without `Authorization` or cookies. Regeneration and new code paths must not route credentials around it.
- Read `GET /api/v1/stream` with `Client::open_stream` (`stream.rs`), which bounds the bytes held for one frame and fails visibly on a malformed one. The generator deliberately emits no method for it; do not add a path that buffers the unbounded stream.
- Keep the public API additive: models and params are `#[non_exhaustive]`, enums keep an `Other(String)` arm, so a regenerate that adds fields or values is not a breaking change.
- No `unwrap` or `expect` outside tests; a panic only for a proven-infallible case, with the reason beside it. Update `ARCHITECTURE.md` when the module layout changes.

## Official resources

| Resource | URL |
| --- | --- |
| Developer portal | https://0xinsider.com/developers |
| API documentation | https://docs.0xinsider.com |
| OpenAPI 3.1 spec | https://0xinsider.com/api/v1/openapi.json |
| Authentication | https://0xinsider.com/auth.md |
| Agent instructions | https://0xinsider.com/agents.md |
| Machine-readable index | https://0xinsider.com/llms.txt |
| Remote MCP endpoint | https://0xinsider.com/mcp |
| Agent Plugin and skills | https://github.com/0xinsider/agent-plugin |
| Python SDK | https://github.com/0xinsider/0xinsider-python |
| Go SDK | https://github.com/0xinsider/0xinsider-go |
| Node.js and TypeScript SDK | https://github.com/0xinsider/0xinsider-node |
| Rust SDK | https://github.com/0xinsider/0xinsider-rust |
| CLI and MCP package | https://www.npmjs.com/package/@0xinsider/mcp |
