#!/usr/bin/env python3
"""Generate the typed Rust client from the 0xinsider OpenAPI document.

Usage:
    python3 scripts/generate.py                 # fetch https://0xinsider.com/api/v1/openapi.json
    python3 scripts/generate.py path/to/openapi.json
    python3 scripts/generate.py --check         # exit 1 when the generated files are stale
    python3 scripts/generate.py --app-commit SHA

Writes, and never hand-edit any of them:
    openapi.json          the document exactly as fetched (the tests read its examples)
    src/models.rs         one Rust type per schema the document names or nests
    src/operations.rs     the operation table, a params struct and a Client method per operation
    src/provenance.rs     which document this release was generated from
    tests/support/generated.rs  operation ids and schema names mapped to Rust types, for the tests

The generator understands every construct the document uses today and raises on
one it does not, rather than emitting an untyped value that hides the gap. The
exceptions are deliberate and listed where they are handled: an untagged
`oneOf`/`anyOf` (a JSON-RPC id that is a string or a number) becomes
`serde_json::Value`, and an integer enum stays `i64`.

The app commit is `--app-commit`, the OXINSIDER_APP_COMMIT environment variable,
or a lookup of the GitHub commits API (GH_TOKEN is used when set). One that cannot
be resolved is recorded as `None` and reported on stderr, never guessed.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.request
from collections import Counter, OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = "https://0xinsider.com/api/v1/openapi.json"
APP_REPOSITORY = "0xinsider/0xinsider"
APP_SPEC_PATH = "web/public/api/v1/openapi.json"
USER_AGENT = "0xinsider-rust-generator"
METHODS = ("get", "post", "put", "patch", "delete")
REDIRECT_CODES = ("301", "302", "303", "307", "308")
HEADER = "// Code generated by scripts/generate.py from the 0xinsider OpenAPI document. DO NOT EDIT.\n"

# POST operations that store nothing: they resolve up to 25 inputs and answer,
# so repeating one is as safe as repeating a GET. Every other write is retried
# only when it documents Idempotency-Key and the caller sent one.
READ_ONLY_POSTS = {"batchGetTraders", "batchGetMarketIntel"}

# Operations that get no generated method, and why.
SKIPPED_OPERATIONS = {
    # An unbounded text/event-stream: read it with Client::open_stream, which
    # delivers frames as they arrive and bounds its memory.
    "getStream": "stream",
    # Documented only to refuse: GET /api/v1/mcp answers 405, the server offers
    # no server-to-client stream.
    "openMcpEventStream": "refused",
}

# Names for enum value sets whose most common property name is too generic to
# stand alone, keyed by the set's first value. A key no set starts with is
# reported and ignored.
ENUM_NAME_OVERRIDES = {
    "bad_request": "ErrorCode",  # ApiError.error.code
    "cursor_expired": "ErrorReason",  # ApiError.error.reason
    "initialize": "McpMethod",  # the MCP JSON-RPC request method
    "provider": "TrustSourceKind",  # TrustSource.kind
    "learn": "ContentKind",  # ContentSearchResult.kind
    "v1": "ExpertDefinition",  # PickOfTheDayQualifyingExpert.source
}

# Names for inline objects whose natural name (owner + property) is a component's.
# Without one the generator falls back to a numbered name (`TraderPnl2`).
INLINE_NAME_OVERRIDES = {
    "TraderPnl": "TraderPnlSummary",  # Trader.pnl; TraderPnl is the P&L history
    "MarketSnapshotFreshness": "MarketSnapshotFreshnessBySource",  # MarketSnapshot.freshness
}

# Headers every operation documents that the client sets itself.
CLIENT_OWNED_HEADERS = {"X-Query-Validation"}

RUST_KEYWORDS = {
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "abstract", "become", "box", "do", "final", "macro", "override", "priv",
    "typeof", "unsized", "virtual", "yield", "try", "gen",
}
NOT_RAW = {"self", "Self", "crate", "super"}


class GenerateError(Exception):
    pass


# --------------------------------------------------------------------------- names


def words(name: str) -> list[str]:
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", name)
    return [w for w in re.split(r"[^0-9A-Za-z]+", name) if w]


def pascal(name: str) -> str:
    out = "".join(w[:1].upper() + w[1:].lower() if w.isupper() and len(w) > 1 else w[:1].upper() + w[1:] for w in words(name))
    if not out:
        raise GenerateError(f"cannot name {name!r}")
    if out[0].isdigit():
        out = "V" + out
    return out


def snake(name: str) -> str:
    out = "_".join(w.lower() for w in words(name))
    if not out:
        raise GenerateError(f"cannot name {name!r}")
    if out[0].isdigit():
        out = "n_" + out
    return out


def field_ident(name: str) -> str:
    ident = snake(name)
    if ident in NOT_RAW:
        return ident + "_"
    if ident in RUST_KEYWORDS:
        return "r#" + ident
    return ident


def bare(ident: str) -> str:
    return ident[2:] if ident.startswith("r#") else ident


def variant_ident(value: str) -> str:
    ident = pascal(value)
    return ident if ident not in RUST_KEYWORDS else ident + "_"


def rust_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


# --------------------------------------------------------------------------- docs


def fix_fences(text: str) -> str:
    """Rewrite code fences so each opening fence is ```text and each closing fence is ```."""
    lines = text.splitlines()
    opened = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("```"):
            lines[i] = "```" if opened else "```text"
            opened = not opened
    if opened:
        lines.append("```")
    return "\n".join(lines)


def docs(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    text = fix_fences(text.strip())
    return [f"{indent}/// {line.strip()}".rstrip() for line in text.splitlines()]


# --------------------------------------------------------------------------- schema helpers


def ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        raise GenerateError(f"unsupported $ref outside components.schemas: {ref}")
    return ref[len(prefix):]


def is_null_schema(schema: dict) -> bool:
    return schema.get("type") == "null" or schema.get("enum") == [None]


def split_nullable(schema: dict) -> tuple[dict, bool]:
    """Return (the schema without its null arm, whether null is allowed)."""
    nullable = bool(schema.get("nullable"))
    schema = dict(schema)
    schema.pop("nullable", None)
    types = schema.get("type")
    if isinstance(types, list):
        if "null" in types:
            nullable = True
        rest = [t for t in types if t != "null"]
        if len(rest) != 1:
            raise GenerateError(f"unsupported multi-type schema {types}")
        schema["type"] = rest[0]
    if isinstance(schema.get("enum"), list) and None in schema["enum"]:
        nullable = True
        schema["enum"] = [v for v in schema["enum"] if v is not None]
    for key in ("oneOf", "anyOf"):
        arms = schema.get(key)
        if isinstance(arms, list) and any(is_null_schema(a) for a in arms):
            nullable = True
            rest = [a for a in arms if not is_null_schema(a)]
            if len(rest) == 1:
                merged = {k: v for k, v in schema.items() if k != key}
                merged.update(rest[0])
                schema = merged
            else:
                schema[key] = rest
    return schema, nullable


def string_enum(schema: dict) -> list[str] | None:
    values = schema.get("enum")
    if not isinstance(values, list):
        return None
    values = [v for v in values if v is not None]
    if not values or not all(isinstance(v, str) for v in values):
        return None
    if len(values) < 2:
        return None  # a single-value enum is a constant; it stays a String
    return values


# --------------------------------------------------------------------------- enum naming


class EnumNames:
    """Names every string enum by its value set, so one set is one Rust type.

    A set a component schema names keeps that name. Otherwise the set is named
    after the property that most often carries it (`grade`, `side`); when two
    sets want one name, the set used more often keeps it and the other is named
    after its first owner plus the property.
    """

    def __init__(self, components: dict):
        self.by_values: dict[tuple, str] = {}
        self.occurrences: OrderedDict[tuple, list[tuple[str, str]]] = OrderedDict()
        for name, schema in components.items():
            values = string_enum(split_nullable(schema)[0])
            if values:
                self.by_values[tuple(values)] = name

    def record(self, values: list[str], owner: str, prop: str) -> None:
        key = tuple(values)
        if key not in self.by_values:
            self.occurrences.setdefault(key, []).append((owner, prop or owner))

    def assign(self, taken: set[str]) -> None:
        wanted: OrderedDict[str, list[tuple[int, tuple]]] = OrderedDict()
        for key, occurrences in self.occurrences.items():
            # `min_grade` and `grade` carry one set; name it after the value, not the filter.
            counts = Counter(re.sub(r"^min_", "", prop) for _, prop in occurrences)
            best = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]
            wanted.setdefault(pascal(best), []).append((len(occurrences), key))
        for key in self.occurrences:
            override = ENUM_NAME_OVERRIDES.get(key[0])
            if override:
                taken.add(override)
                self.by_values[key] = override
        unused = set(ENUM_NAME_OVERRIDES) - {key[0] for key in self.occurrences}
        for first in sorted(unused):
            print(f"warning: ENUM_NAME_OVERRIDES[{first!r}] matches no enum; remove it", file=sys.stderr)
        for name, claims in wanted.items():
            claims = [claim for claim in claims if claim[1] not in self.by_values]
            claims.sort(key=lambda claim: -claim[0])
            for index, (_, key) in enumerate(claims):
                candidate = name
                if index > 0 or candidate in taken:
                    owner, prop = self.occurrences[key][0]
                    candidate = pascal(owner) + pascal(prop)
                base, n = candidate, 2
                while candidate in taken:
                    candidate, n = f"{base}{n}", n + 1
                taken.add(candidate)
                self.by_values[key] = candidate

    def name(self, values: list[str]) -> str:
        return self.by_values[tuple(values)]

    def names(self) -> set[str]:
        return set(self.by_values.values())


def collect_enums(node, enums: EnumNames, owner: str, prop: str) -> None:
    """Record each inline string enum under a schema with the property that carries it."""
    if isinstance(node, list):
        for item in node:
            collect_enums(item, enums, owner, prop)
        return
    if not isinstance(node, dict) or "$ref" in node:
        return
    values = string_enum(split_nullable(node)[0])
    if values:
        enums.record(values, owner, prop)
    for key, value in node.items():
        if key == "properties" and isinstance(value, dict):
            for name, child in value.items():
                collect_enums(child, enums, owner + pascal(prop) if prop else owner, name)
        elif key in ("items", "additionalProperties", "oneOf", "anyOf", "allOf"):
            collect_enums(value, enums, owner, prop)


# --------------------------------------------------------------------------- type model


class Field:
    def __init__(self, json_name: str, ident: str, rust_type: str, doc: str | None,
                 required: bool, nullable: bool, flatten: bool = False):
        self.json_name = json_name
        self.ident = ident
        self.rust_type = rust_type
        self.doc = doc
        self.required = required
        self.nullable = nullable
        self.flatten = flatten

    @property
    def optional(self) -> bool:
        return not self.flatten and (not self.required or self.nullable)


class Param:
    """One operation parameter as the generated method sees it."""

    def __init__(self, spec: dict, ident: str, rust_type: str):
        self.spec = spec
        self.name = spec["name"]
        self.location = spec["in"]
        self.ident = ident
        self.rust_type = rust_type


class Generator:
    def __init__(self, doc: dict):
        self.doc = doc
        self.components: dict = doc.get("components", {}).get("schemas", {})
        self.enums = EnumNames(self.components)
        self.enum_defs: OrderedDict[str, tuple[list[str], str | None]] = OrderedDict()
        self.structs: OrderedDict[str, tuple[list[Field], str | None]] = OrderedDict()
        self.unions: OrderedDict[str, tuple[str, list[tuple[str, str, str]], str | None]] = OrderedDict()
        self.aliases: OrderedDict[str, tuple[str, str | None]] = OrderedDict()
        self.params: OrderedDict[str, list[str]] = OrderedDict()
        self.request_roots: set[str] = set()
        self.boxed_edges: set[tuple[str, str]] = set()
        self.list_pages: dict[str, tuple[str, bool, bool, bool]] = {}
        self.cursor_params: set[str] = set()
        self.response_types: OrderedDict[str, str] = OrderedDict()
        self.name_owner: dict[str, str] = {}
        self.body_types: OrderedDict[str, str] = OrderedDict()

    # ---------------------------------------------------------------- walk

    def operations(self):
        for path, item in self.doc.get("paths", {}).items():
            for method in METHODS:
                operation = item.get(method)
                if isinstance(operation, dict):
                    yield operation["operationId"], method, path, operation

    def resolve_param(self, param: dict) -> dict:
        if "$ref" not in param:
            return param
        prefix = "#/components/parameters/"
        ref = param["$ref"]
        if not ref.startswith(prefix):
            raise GenerateError(f"unsupported parameter $ref {ref}")
        return self.doc["components"]["parameters"][ref[len(prefix):]]

    def json_body_schema(self, operation: dict):
        body = operation.get("requestBody")
        if not body:
            return None
        content = body.get("content") or {}
        if "application/json" not in content:
            raise GenerateError(f"{operation['operationId']}: unsupported request body {list(content)}")
        return content["application/json"].get("schema")

    def success(self, operation: dict) -> tuple[str, str, dict | None, bool]:
        """(kind, accept, schema, may_be_empty); kind is json, text or download."""
        responses = operation.get("responses", {})
        codes = sorted(c for c in responses if c.startswith("2"))
        if not codes:
            if any(c in responses for c in REDIRECT_CODES):
                return "download", "*/*", None, False
            raise GenerateError(f"{operation['operationId']} documents no 2xx and no redirect")
        schemas, empty = [], False
        for code in codes:
            content = responses[code].get("content") or {}
            if not content:
                empty = True
            elif "application/json" in content:
                schemas.append(content["application/json"].get("schema"))
            elif all(media.startswith("text/") and media != "text/event-stream" for media in content):
                return "text", next(iter(content)), None, False
            else:
                raise GenerateError(f"{operation['operationId']}: unsupported success media {list(content)}")
        if not schemas:
            raise GenerateError(f"{operation['operationId']}: no success body")
        first = json.dumps(schemas[0], sort_keys=True)
        if any(json.dumps(s, sort_keys=True) != first for s in schemas[1:]):
            raise GenerateError(f"{operation['operationId']}: 2xx responses carry different schemas")
        return "json", "application/json", schemas[0], empty

    # ---------------------------------------------------------------- preparation

    def prepare_enums(self) -> None:
        for name, schema in self.components.items():
            collect_enums(schema, self.enums, name, "")
        for op_id, _, _, operation in self.operations():
            owner = pascal(op_id)
            for param in operation.get("parameters", []):
                param = self.resolve_param(param)
                collect_enums(param.get("schema", {}), self.enums, owner, param["name"])
            body = self.json_body_schema(operation)
            if body is not None:
                collect_enums(body, self.enums, owner + "Body", "")
            for code, response in operation.get("responses", {}).items():
                schema = (response.get("content") or {}).get("application/json", {}).get("schema")
                if schema is not None and code.startswith("2"):
                    collect_enums(schema, self.enums, owner + "Response", "")
        self.enums.assign(set(self.components) | {"Client", "Error", "Result", "Operation", "Download"})

    def find_boxed_edges(self) -> None:
        """Box a direct (non-collection) reference that closes a cycle."""
        graph = {name: set(self.direct_refs(schema)) for name, schema in self.components.items()}

        def reaches(start: str, goal: str) -> bool:
            seen, stack = set(), [start]
            while stack:
                node = stack.pop()
                if node == goal:
                    return True
                if node not in seen:
                    seen.add(node)
                    stack.extend(graph.get(node, ()))
            return False

        for name, targets in graph.items():
            for target in targets:
                if reaches(target, name):
                    self.boxed_edges.add((name, target))

    def direct_refs(self, schema) -> list[str]:
        if not isinstance(schema, dict):
            return []
        if "$ref" in schema:
            return [ref_name(schema["$ref"])]
        out: list[str] = []
        for child in (schema.get("properties") or {}).values():
            out.extend(self.direct_refs(child))
        for key in ("allOf", "oneOf", "anyOf"):
            for child in schema.get(key) or []:
                out.extend(self.direct_refs(child))
        return out

    def component_nullable(self, name: str) -> bool:
        return split_nullable(self.components[name])[1]

    # ---------------------------------------------------------------- types

    def type_name(self, hint: str, schema: dict, exact: bool) -> str:
        """The Rust name for a nested object or union. A component keeps its own
        name (`exact`); an inline schema takes `hint` unless a component, an enum
        or a different inline schema already has it, and then `hint2`, `hint3`, ..."""
        key = json.dumps(schema, sort_keys=True)
        if exact:
            self.name_owner[hint] = key
            return hint
        candidate, n = hint, 2
        if hint in INLINE_NAME_OVERRIDES and (hint in self.components or self.name_owner.get(hint, key) != key):
            hint = candidate = INLINE_NAME_OVERRIDES[hint]
        while True:
            owner = self.name_owner.get(candidate)
            if owner == key:
                return candidate
            if owner is None and candidate not in self.components and candidate not in self.enums.names():
                self.name_owner[candidate] = key
                return candidate
            candidate, n = f"{hint}{n}", n + 1

    def rust_type(self, schema: dict, hint: str, owner: str, exact: bool = False) -> tuple[str, bool]:
        """Return (rust type, nullable) for a schema, defining any type it nests."""
        if not isinstance(schema, dict):
            raise GenerateError(f"schema for {hint} is not an object")
        schema, nullable = split_nullable(schema)
        if "$ref" in schema:
            target = ref_name(schema["$ref"])
            if target not in self.components:
                raise GenerateError(f"$ref names a schema the document does not define: {target}")
            rust = f"Box<{target}>" if (owner, target) in self.boxed_edges else target
            return rust, nullable or self.component_nullable(target)
        if "allOf" in schema:
            arms = schema["allOf"]
            if len(arms) == 1 and not schema.get("properties"):
                inner, inner_nullable = self.rust_type(arms[0], hint, owner)
                return inner, nullable or inner_nullable
            name = self.type_name(hint, schema, exact)
            self.define_struct(name, schema)
            return name, nullable
        if "oneOf" in schema or "anyOf" in schema:
            arms = schema.get("oneOf") or schema.get("anyOf")
            if schema.get("discriminator") and all("$ref" in arm for arm in arms):
                name = self.type_name(hint, schema, exact)
                self.define_union(name, schema)
                return name, nullable
            # Deliberately untyped: an untagged union of scalars (a JSON-RPC id).
            return "serde_json::Value", nullable
        kind = schema.get("type")
        if kind is None:
            if "properties" in schema:
                kind = "object"
            elif isinstance(schema.get("const"), str) or string_enum(schema):
                kind = "string"
            else:
                return "serde_json::Value", nullable
        if kind == "string":
            values = string_enum(schema)
            if values:
                name = self.enums.name(values)
                if name not in self.enum_defs:
                    self.enum_defs[name] = (values, None)
                return name, nullable
            return "String", nullable
        if kind == "integer":
            return "i64", nullable
        if kind == "number":
            return "f64", nullable
        if kind == "boolean":
            return "bool", nullable
        if kind == "array":
            items = schema.get("items")
            if items is None:
                return "Vec<serde_json::Value>", nullable
            inner, inner_nullable = self.rust_type(items, hint + "Item", owner)
            if inner.startswith("Box<"):
                inner = inner[4:-1]  # a Vec already puts its elements on the heap
            return (f"Vec<Option<{inner}>>" if inner_nullable else f"Vec<{inner}>"), nullable
        if kind == "object":
            if schema.get("properties"):
                name = self.type_name(hint, schema, exact)
                self.define_struct(name, schema)
                return name, nullable
            extra = schema.get("additionalProperties")
            if isinstance(extra, dict) and extra:
                inner, inner_nullable = self.rust_type(extra, hint + "Value", owner)
                inner = f"Option<{inner}>" if inner_nullable else inner
                return f"std::collections::BTreeMap<String, {inner}>", nullable
            return "serde_json::Map<String, serde_json::Value>", nullable
        raise GenerateError(f"unsupported schema type {kind!r} at {hint}")

    def define_struct(self, name: str, schema: dict) -> None:
        if name in self.structs:
            return
        self.structs[name] = ([], None)  # reserve the name before recursing
        fields: list[Field] = []
        for arm in schema.get("allOf") or []:
            if "$ref" in arm:
                target = ref_name(arm["$ref"])
                fields.append(Field(target, field_ident(target), target, None, True, False, flatten=True))
            else:
                fields.extend(self.object_fields(name, split_nullable(arm)[0]))
        fields.extend(self.object_fields(name, schema))
        if schema.get("additionalProperties") is True:
            fields.append(Field("", "extra", "serde_json::Map<String, serde_json::Value>",
                                "Keys this release does not name. The API adds fields additively; they are kept here.",
                                True, False, flatten=True))
        idents = [f.ident for f in fields]
        if len(set(idents)) != len(idents):
            raise GenerateError(f"{name} has two fields with one Rust name: {idents}")
        self.structs[name] = (fields, schema.get("description"))

    def object_fields(self, owner: str, schema: dict) -> list[Field]:
        required = set(schema.get("required") or [])
        fields = []
        for json_name, prop in (schema.get("properties") or {}).items():
            rust, nullable = self.rust_type(prop, owner + pascal(json_name), owner)
            description = prop.get("description") if isinstance(prop, dict) else None
            fields.append(Field(json_name, field_ident(json_name), rust, description, json_name in required, nullable))
        return fields

    def define_union(self, name: str, schema: dict) -> None:
        if name in self.unions:
            return
        discriminator = schema["discriminator"]
        tag = discriminator["propertyName"]
        by_target = {ref_name(v): k for k, v in (discriminator.get("mapping") or {}).items()}
        variants = []
        for arm in schema.get("oneOf") or schema.get("anyOf"):
            target = ref_name(arm["$ref"])
            if target not in by_target:
                raise GenerateError(f"{name}: {target} has no discriminator mapping value")
            variants.append((variant_ident(by_target[target]), by_target[target], target))
        self.unions[name] = (tag, variants, schema.get("description"))

    # ---------------------------------------------------------------- request-ness

    def request_types(self) -> set[str]:
        """Every struct or union a caller builds: request bodies and what they nest."""
        known = set(self.structs) | set(self.unions) | set(self.aliases)
        out, stack = set(), list(self.request_roots)
        while stack:
            name = stack.pop()
            if name in out or name not in known:
                continue
            out.add(name)
            referenced: list[str] = []
            if name in self.structs:
                referenced = [f.rust_type for f in self.structs[name][0]]
            elif name in self.unions:
                referenced = [target for _, _, target in self.unions[name][1]]
            elif name in self.aliases:
                referenced = [self.aliases[name][0]]
            for rust in referenced:
                stack.extend(re.findall(r"[A-Z][A-Za-z0-9]*", rust))
        return out

    # ---------------------------------------------------------------- generate

    def generate(self) -> tuple[str, str, int]:
        self.prepare_enums()
        self.find_boxed_edges()
        for name, schema in self.components.items():
            stripped, _ = split_nullable(schema)
            values = string_enum(stripped)
            if values:
                self.enum_defs[name] = (values, schema.get("description"))
                continue
            rust, _ = self.rust_type(schema, name, name, exact=True)
            if rust != name:
                self.aliases[name] = (rust, schema.get("description"))

        table: list[str] = []
        methods: list[str] = []
        count = 0
        for op_id, method, path, operation in self.operations():
            count += 1
            if op_id in SKIPPED_OPERATIONS:
                table.append(self.operation_const(op_id, method, path, operation, "text/event-stream" if SKIPPED_OPERATIONS[op_id] == "stream" else "application/json"))
                continue
            kind, accept, schema, may_be_empty = self.success(operation)
            table.append(self.operation_const(op_id, method, path, operation, accept))
            methods.extend(self.operation_method(op_id, method, path, operation, kind, schema, may_be_empty))
            methods.append("")
        return self.render_models(), self.render_operations(table, methods), count

    def operation_const(self, op_id: str, method: str, path: str, operation: dict, accept: str) -> str:
        params = [self.resolve_param(p) for p in operation.get("parameters", [])]
        keyed = any(p["in"] == "header" and p["name"].lower() == "idempotency-key" for p in params)
        if method == "get" or op_id in READ_ONLY_POSTS:
            retry = "RetryClass::Read"
        elif keyed:
            retry = "RetryClass::Keyed"
        else:
            retry = "RetryClass::Never"
        security = operation.get("security", self.doc.get("security", []))
        return (
            f"    /// `{method.upper()} {path}`\n"
            f"    pub const {snake(op_id).upper()}: Operation = Operation {{\n"
            f"        id: {rust_str(op_id)},\n"
            f"        method: {rust_str(method.upper())},\n"
            f"        path: {rust_str(path)},\n"
            f"        accept: {rust_str(accept)},\n"
            f"        retry: {retry},\n"
            f"        requires_credential: {'true' if security else 'false'},\n"
            f"    }};"
        )

    def param_type(self, param: dict, owner: str) -> str:
        rust, _ = self.rust_type(param.get("schema", {}), owner + pascal(param["name"]), owner)
        return rust

    def operation_method(self, op_id, method, path, operation, kind, schema, may_be_empty) -> list[str]:
        name = snake(op_id)
        prefix = pascal(op_id)
        specs = [self.resolve_param(p) for p in operation.get("parameters", [])]
        if any(p["in"] == "cookie" for p in specs):
            raise GenerateError(f"{op_id}: cookie parameters are not supported")
        path_params = [p for p in specs if p["in"] == "path"]
        # `expand[]` and `wallet[]` are backward-compatible spellings of `expand`
        # and `wallet`; this client always sends the canonical name.
        query = [p for p in specs if p["in"] == "query" and not p["name"].endswith("[]")]
        headers = [p for p in specs if p["in"] == "header" and p["name"] not in CLIENT_OWNED_HEADERS]
        required = [Param(p, field_ident(p["name"]), self.param_type(p, prefix)) for p in query if p.get("required")]
        optional = [Param(p, field_ident(p["name"]), self.param_type(p, prefix)) for p in query if not p.get("required")]
        optional += [Param(p, field_ident(p["name"]), "String") for p in headers]

        if kind == "json":
            response_type, _ = self.rust_type(schema, prefix + "Response", prefix + "Response")
            returns = f"Option<{response_type}>" if may_be_empty else response_type
            self.response_types[op_id] = response_type
        elif kind == "text":
            response_type = returns = "String"
        else:
            response_type = returns = "Download"

        body_type = None
        body_schema = self.json_body_schema(operation)
        if body_schema is not None:
            body_type, _ = self.rust_type(body_schema, prefix + "Body", prefix + "Body")
            self.body_types[op_id] = body_type
            self.request_roots.update(re.findall(r"[A-Z][A-Za-z0-9]*", body_type))

        args: list[str] = []
        path_expr, fmt_args = path, []
        for p in path_params:
            ident = field_ident(p["name"])
            kind_ = (p.get("schema") or {}).get("type")
            if kind_ == "integer":
                args.append(f"{ident}: i64")
                fmt_args.append(f"{bare(ident)} = {ident}")
            elif kind_ == "string":
                args.append(f"{ident}: &str")
                fmt_args.append(f"{bare(ident)} = encode_path_segment({ident})")
            else:
                raise GenerateError(f"{op_id}: unsupported path parameter type {kind_}")
            path_expr = path_expr.replace("{" + p["name"] + "}", "{" + bare(ident) + "}")
        for param in required:
            if param.rust_type.startswith("Vec<"):
                raise GenerateError(f"{op_id}: a required array query parameter is not supported")
            args.append(f"{param.ident}: {'&str' if param.rust_type == 'String' else param.rust_type}")
        if body_type is not None:
            args.append(f"body: &{body_type}")
        params_type = None
        if optional:
            params_type = prefix + "Params"
            args.append(f"params: &{params_type}")
            self.params[params_type] = self.render_params(params_type, op_id, method, path, optional)
            if any(p.ident == "cursor" for p in optional):
                self.cursor_params.add(params_type)

        lines = [f"    /// {(operation.get('summary') or op_id).strip()}", "    ///", f"    /// `{method.upper()} {path}`"]
        if operation.get("description"):
            lines.append("    ///")
            lines.extend(docs(operation["description"], "    "))
        if kind == "download":
            lines += [
                "    ///",
                "    /// The API answers with a redirect to the file. It is followed once, by a fresh",
                "    /// request that carries no credential, and the file comes back as a streaming",
                "    /// [`Download`].",
            ]
        if may_be_empty:
            lines += ["    ///", "    /// Returns `None` when the API answers with an empty success body."]
        lines.append(f"    pub async fn {name}({', '.join(['&self'] + args)}) -> Result<{returns}> {{")
        if fmt_args:
            lines.append(f"        let path = format!({rust_str(path_expr)}, {', '.join(fmt_args)});")
        else:
            lines.append(f"        let path = String::from({rust_str(path)});")
        mutable = bool(required or optional or body_type)
        lines.append(f"        let {'mut ' if mutable else ''}call = Call::new(&Operation::{snake(op_id).upper()}, path);")
        for param in required:
            lines.append(f"        call.query({rust_str(param.name)}, {self.query_value(param.ident, param.rust_type)});")
        for param in optional:
            if param.location == "header":
                lines.append(f"        call.header({rust_str(param.name)}, params.{param.ident}.as_deref());")
            elif param.rust_type.startswith("Vec<"):
                lines.append(f"        for value in &params.{param.ident} {{")
                lines.append(f"            call.query({rust_str(param.name)}, {self.query_value('value', param.rust_type[4:-1])});")
                lines.append("        }")
            else:
                lines.append(f"        if let Some(value) = &params.{param.ident} {{")
                lines.append(f"            call.query({rust_str(param.name)}, {self.query_value('value', param.rust_type)});")
                lines.append("        }")
        if body_type is not None:
            lines.append("        call.json(body)?;")
        send = {"json": "send_json_optional" if may_be_empty else "send_json", "text": "send_text", "download": "send_download"}[kind]
        lines.append(f"        self.{send}(call).await")
        lines.append("    }")

        if kind == "json" and not may_be_empty and response_type in self.structs:
            fields = {f.json_name: f for f in self.structs[response_type][0]}
            data, has_more, cursor = fields.get("data"), fields.get("has_more"), fields.get("next_cursor")
            if data and has_more and cursor and data.rust_type.startswith("Vec<") and cursor.rust_type == "String":
                self.list_pages[response_type] = (data.rust_type[4:-1], data.optional, has_more.optional, cursor.optional)
        return lines

    def query_value(self, ident: str, rust: str) -> str:
        if rust == "String":
            return f"{ident}.to_string()"
        if rust in ("i64", "f64", "bool"):
            return f"{ident}.to_string()"
        if rust in self.enum_defs:
            return f"{ident}.as_str().to_owned()"
        raise GenerateError(f"unsupported query parameter type {rust}")

    def render_params(self, name: str, op_id: str, method: str, path: str, fields: list[Param]) -> list[str]:
        lines = [
            f"/// Optional parameters for [`Client::{snake(op_id)}`] (`{method.upper()} {path}`).",
            "///",
            "/// Start from `Default::default()` and set what you need, through the field or the",
            "/// chainable setter of the same name.",
            "#[derive(Debug, Clone, Default, PartialEq)]",
            "#[non_exhaustive]",
            f"pub struct {name} {{",
        ]
        for param in fields:
            lines.extend(docs(param.spec.get("description"), "    "))
            if param.location == "header":
                lines.append("    ///")
                lines.append(f"    /// Sent as the `{param.name}` header.")
            ty = param.rust_type if param.rust_type.startswith("Vec<") else f"Option<{param.rust_type}>"
            lines.append(f"    pub {param.ident}: {ty},")
        lines.append("}")
        lines.append("")
        lines.append(f"impl {name} {{")
        for param in fields:
            lines.append(f"    /// Sets `{param.name}`.")
            lines.append("    #[must_use]")
            if param.rust_type.startswith("Vec<"):
                inner = param.rust_type[4:-1]
                if inner == "String":
                    lines.append(f"    pub fn {param.ident}<I, S>(mut self, values: I) -> Self")
                    lines.append("    where")
                    lines.append("        I: IntoIterator<Item = S>,")
                    lines.append("        S: Into<String>,")
                    lines.append("    {")
                    lines.append(f"        self.{param.ident} = values.into_iter().map(Into::into).collect();")
                else:
                    lines.append(f"    pub fn {param.ident}<I: IntoIterator<Item = {inner}>>(mut self, values: I) -> Self {{")
                    lines.append(f"        self.{param.ident} = values.into_iter().collect();")
            elif param.rust_type == "String":
                lines.append(f"    pub fn {param.ident}(mut self, value: impl Into<String>) -> Self {{")
                lines.append(f"        self.{param.ident} = Some(value.into());")
            else:
                lines.append(f"    pub fn {param.ident}(mut self, value: {param.rust_type}) -> Self {{")
                lines.append(f"        self.{param.ident} = Some(value);")
            lines.append("        self")
            lines.append("    }")
        lines.append("}")
        return lines

    # ---------------------------------------------------------------- render

    def render_test_support(self) -> str:
        """Maps operation ids and schema names to their Rust types, for the
        tests that decode every documented example (and live sandbox answers)."""

        def arms(mapping) -> list[str]:
            return [f"        {rust_str(key)} => Some(check::<{rust}>(value))," for key, rust in mapping]

        components = [(name, name) for name in self.components if name in self.structs or name in self.unions
                      or name in self.enum_defs or name in self.aliases]
        out = [
            HEADER,
            "//! Operation ids and schema names mapped to their Rust types, for the example tests.",
            "",
            "#![allow(dead_code)]",
            "",
            "use oxinsider::models::*;",
            "",
            "fn check<T: serde::de::DeserializeOwned>(value: serde_json::Value) -> Result<(), String> {",
            "    serde_path_to_error::deserialize::<_, T>(value).map(drop).map_err(|error| format!(\"at `{}`: {}\", error.path(), error.inner()))",
            "}",
            "",
            "/// Decode a 2xx body of `operation` into its response type.",
            "pub fn decode_response(operation: &str, value: serde_json::Value) -> Option<Result<(), String>> {",
            "    match operation {",
            *arms(self.response_types.items()),
            "        _ => None,",
            "    }",
            "}",
            "",
            "/// Decode a request body of `operation` into its body type.",
            "pub fn decode_body(operation: &str, value: serde_json::Value) -> Option<Result<(), String>> {",
            "    match operation {",
            *arms(self.body_types.items()),
            "        _ => None,",
            "    }",
            "}",
            "",
            "/// Decode a value into the type for a component schema.",
            "pub fn decode_component(name: &str, value: serde_json::Value) -> Option<Result<(), String>> {",
            "    match name {",
            *arms(components),
            "        _ => None,",
            "    }",
            "}",
        ]
        return "\n".join(out).rstrip() + "\n"

    def render_struct(self, name: str, request: bool) -> list[str]:
        fields, description = self.structs[name]
        derives = ["Debug", "Clone", "PartialEq", "Serialize", "Deserialize"]
        if request and all(f.optional for f in fields):
            derives.append("Default")
        lines = docs(description)
        lines.append(f"#[derive({', '.join(derives)})]")
        if not request:
            lines.append("#[non_exhaustive]")
        lines.append(f"pub struct {name} {{")
        for field in fields:
            lines.extend(docs(field.doc, "    "))
            attrs = []
            if field.flatten:
                attrs.append("flatten")
            else:
                if bare(field.ident) != field.json_name:
                    attrs.append(f"rename = {rust_str(field.json_name)}")
                if field.optional:
                    attrs.append("default")
                if not field.required:
                    attrs.append('skip_serializing_if = "Option::is_none"')
            if attrs:
                lines.append(f"    #[serde({', '.join(attrs)})]")
            rust = f"Option<{field.rust_type}>" if field.optional else field.rust_type
            lines.append(f"    pub {field.ident}: {rust},")
        lines.append("}")
        return lines

    def render_union(self, name: str) -> list[str]:
        tag, variants, description = self.unions[name]
        lines = docs(description)
        if lines:
            lines.append("///")
        lines += [
            f"/// Discriminated by `{tag}`. A `{tag}` this release does not know is kept whole in",
            "/// `Unknown`, so a new kind never fails a response.",
            "#[derive(Debug, Clone, PartialEq)]",
            "#[non_exhaustive]",
            f"pub enum {name} {{",
        ]
        for ident, value, target in variants:
            lines.append(f"    /// `{tag}` is `{value}`.")
            lines.append(f"    {ident}({target}),")
        lines.append(f"    /// A `{tag}` this release does not know, kept as sent.")
        lines.append("    Unknown(serde_json::Value),")
        lines.append("}")
        lines.append("")
        lines.append(f"impl<'de> Deserialize<'de> for {name} {{")
        lines.append("    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {")
        lines.append("        let value = serde_json::Value::deserialize(deserializer)?;")
        lines.append(f"        match value.get({rust_str(tag)}).and_then(serde_json::Value::as_str) {{")
        for ident, value, _ in variants:
            lines.append(f"            Some({rust_str(value)}) => serde_json::from_value(value).map(Self::{ident}).map_err(de::Error::custom),")
        lines.append("            _ => Ok(Self::Unknown(value)),")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"impl Serialize for {name} {{")
        lines.append("    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {")
        lines.append("        match self {")
        for ident, _, _ in variants:
            lines.append(f"            Self::{ident}(inner) => inner.serialize(serializer),")
        lines.append("            Self::Unknown(inner) => inner.serialize(serializer),")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        return lines

    def render_enum(self, name: str, values: list[str], description: str | None) -> list[str]:
        idents = [variant_ident(v) for v in values]
        if len(set(idents)) != len(idents) or "Other" in idents:
            raise GenerateError(f"enum {name} has colliding variants {values}")
        lines = docs(description)
        if lines:
            lines.append("///")
        lines += [
            "/// A value this release does not know is kept in `Other`, so a new value never fails a response.",
            "#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]",
            "#[non_exhaustive]",
            f"pub enum {name} {{",
        ]
        for ident, value in zip(idents, values):
            lines.append(f"    /// `{value}`")
            lines.append(f"    #[serde(rename = {rust_str(value)})]")
            lines.append(f"    {ident},")
        lines += [
            "    /// A value this release does not know, kept as sent.",
            "    #[serde(untagged)]",
            "    Other(String),",
            "}",
            "",
            f"impl {name} {{",
            "    /// The value as the API spells it.",
            "    pub fn as_str(&self) -> &str {",
            "        match self {",
        ]
        for ident, value in zip(idents, values):
            lines.append(f"            Self::{ident} => {rust_str(value)},")
        lines += [
            "            Self::Other(value) => value,",
            "        }",
            "    }",
            "}",
            "",
            f"impl From<&str> for {name} {{",
            "    fn from(value: &str) -> Self {",
            "        match value {",
        ]
        for ident, value in zip(idents, values):
            lines.append(f"            {rust_str(value)} => Self::{ident},")
        lines += [
            "            other => Self::Other(other.to_owned()),",
            "        }",
            "    }",
            "}",
            "",
            f"impl std::fmt::Display for {name} {{",
            "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
            "        f.write_str(self.as_str())",
            "    }",
            "}",
            "",
            f"impl AsRef<str> for {name} {{",
            "    fn as_ref(&self) -> &str {",
            "        self.as_str()",
            "    }",
            "}",
        ]
        return lines

    def render_models(self) -> str:
        request = self.request_types()
        blocks: list[tuple[str, list[str]]] = []
        for name in self.structs:
            blocks.append((name, self.render_struct(name, name in request)))
        for name in self.unions:
            blocks.append((name, self.render_union(name)))
        for name, (values, description) in self.enum_defs.items():
            blocks.append((name, self.render_enum(name, values, description)))
        for name, (rust, description) in self.aliases.items():
            blocks.append((name, docs(description) + [f"pub type {name} = {rust};"]))
        names = [n for n, _ in blocks]
        if len(set(names)) != len(names):
            raise GenerateError(f"two types share a name: {sorted(n for n in names if names.count(n) > 1)}")
        blocks.sort(key=lambda block: block[0])
        uses = "use serde::{de, Deserialize, Deserializer, Serialize, Serializer};" if self.unions else "use serde::{Deserialize, Serialize};"
        out = [
            HEADER,
            "//! Typed models for every schema the OpenAPI document names, and for the request",
            "//! and response bodies it defines inline.",
            "//!",
            "//! A field the document marks optional or nullable is an `Option`: `None` means the",
            "//! API did not report that value, which is not a zero. Unknown JSON keys are ignored",
            "//! and an unknown enum value lands in `Other`, so an additive API change never fails",
            "//! a response. Money and price fields are `f64`, the precision the API sends.",
            "",
            "// Descriptions are the document's own, quoted verbatim; a field it leaves",
            "// undescribed has no doc comment rather than an invented one.",
            "#![allow(missing_docs)]",
            "#![allow(rustdoc::bare_urls, rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]",
            "#![allow(clippy::doc_lazy_continuation, clippy::large_enum_variant)]",
            "",
            uses,
            "",
        ]
        for _, lines in blocks:
            out.extend(lines)
            out.append("")
        return "\n".join(out).rstrip() + "\n"

    def render_operations(self, table: list[str], methods: list[str]) -> str:
        consts = re.findall(r"pub const ([A-Z0-9_]+): Operation", "\n".join(table))
        out = [
            HEADER,
            "//! The operation table, and one `Client` method per operation in the OpenAPI document.",
            "",
            "#![allow(rustdoc::bare_urls, rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]",
            "#![allow(clippy::doc_lazy_continuation, clippy::too_many_arguments)]",
            "",
            "use crate::client::{encode_path_segment, Call};",
            "use crate::models::*;",
            "use crate::pagination::{CursorParams, ListPage};",
            "use crate::{Client, Download, Operation, Result, RetryClass};",
            "",
            "impl Operation {",
        ]
        out.extend(table)
        out += [
            "}",
            "",
            "/// Every operation in the OpenAPI document, in document order.",
            "pub const OPERATIONS: &[Operation] = &[",
        ]
        out += [f"    Operation::{c}," for c in consts]
        out += ["];", ""]
        for lines in self.params.values():
            out.extend(lines)
            out.append("")
        out.append("impl Client {")
        out.extend(methods)
        while out[-1] == "":
            out.pop()
        out += ["}", ""]
        for response_type, (item, data_optional, has_more_optional, cursor_optional) in sorted(self.list_pages.items()):
            out += [
                f"impl ListPage for {response_type} {{",
                f"    type Item = {item};",
                "",
                f"    fn items(&self) -> &[{item}] {{",
                "        self.data.as_deref().unwrap_or_default()" if data_optional else "        &self.data",
                "    }",
                "",
                f"    fn into_items(self) -> Vec<{item}> {{",
                "        self.data.unwrap_or_default()" if data_optional else "        self.data",
                "    }",
                "",
                "    fn has_more(&self) -> bool {",
                "        self.has_more.unwrap_or(false)" if has_more_optional else "        self.has_more",
                "    }",
                "",
                "    fn next_cursor(&self) -> Option<&str> {",
                "        self.next_cursor.as_deref()" if cursor_optional else "        Some(&self.next_cursor)",
                "    }",
                "}",
                "",
            ]
        for params_type in sorted(self.cursor_params):
            out += [
                f"impl CursorParams for {params_type} {{",
                "    fn set_cursor(&mut self, cursor: Option<String>) {",
                "        self.cursor = cursor;",
                "    }",
                "}",
                "",
            ]
        return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- provenance


def load(source: str) -> bytes:
    if source.startswith(("http://", "https://")):
        request = urllib.request.Request(source, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310 - fixed https source
            return response.read()
    return Path(source).read_bytes()


def resolve_app_commit(explicit: str | None) -> str | None:
    candidate = explicit or os.environ.get("OXINSIDER_APP_COMMIT")
    if candidate:
        return candidate
    url = f"https://api.github.com/repos/{APP_REPOSITORY}/commits?path={APP_SPEC_PATH}&per_page=1"
    headers = {"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=30) as response:  # noqa: S310
            commits = json.load(response)
    except (OSError, ValueError) as error:
        print(f"warning: app commit not resolved from the GitHub API ({error}); recording None", file=sys.stderr)
        return None
    if not isinstance(commits, list) or not commits:
        print("warning: the GitHub API listed no commit for the document; recording None", file=sys.stderr)
        return None
    return str(commits[0]["sha"])


def render_provenance(raw: bytes, doc: dict, source: str, app_commit: str | None, count: int) -> str:
    version = doc.get("info", {}).get("version", "unknown")
    commit = "None" if app_commit is None else f"Some({rust_str(app_commit)})"
    return (
        HEADER
        + "//! Which OpenAPI document this release was generated from.\n"
        "//!\n"
        "//! Compare [`OPENAPI_SHA256`] with `shasum -a 256` of\n"
        "//! <https://0xinsider.com/api/v1/openapi.json> to see whether a release is behind the API.\n"
        "\n"
        "/// Where the document came from: the published URL, or the app repository path when generated from a file.\n"
        f"pub const OPENAPI_SOURCE: &str = {rust_str(source)};\n"
        "/// SHA-256 of the document bytes as fetched.\n"
        f"pub const OPENAPI_SHA256: &str = {rust_str(hashlib.sha256(raw).hexdigest())};\n"
        "/// The document's `info.version`.\n"
        f"pub const OPENAPI_VERSION: &str = {rust_str(version)};\n"
        "/// Operations in the document, including the two read by hand (the stream) or refused (`GET /api/v1/mcp`).\n"
        f"pub const OPERATION_COUNT: usize = {count};\n"
        "/// The repository that owns the document.\n"
        f"pub const APP_REPOSITORY: &str = {rust_str(APP_REPOSITORY)};\n"
        "/// The document's path in that repository.\n"
        f"pub const APP_SPEC_PATH: &str = {rust_str(APP_SPEC_PATH)};\n"
        "/// The app repository commit that last changed the document, or `None` when it could not be resolved.\n"
        f"pub const APP_COMMIT: Option<&str> = {commit};\n"
    )


def rustfmt(text: str) -> str:
    """Format generated Rust the way `cargo fmt` would, so the files never drift from it."""
    result = subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=text, capture_output=True, text=True, cwd=ROOT, check=False,
    )
    if result.returncode != 0:
        raise GenerateError(f"rustfmt failed:\n{result.stderr}")
    return result.stdout


def main(argv: list[str]) -> int:
    check = "--check" in argv
    argv = [a for a in argv if a != "--check"]
    app_commit = None
    if "--app-commit" in argv:
        index = argv.index("--app-commit")
        app_commit = argv[index + 1]
        del argv[index : index + 2]
    source = argv[0] if argv else (str(ROOT / "openapi.json") if check else DEFAULT_SOURCE)
    raw = load(source)
    doc = json.loads(raw)
    generator = Generator(doc)
    try:
        models, operations, count = generator.generate()
    except GenerateError as error:
        print(f"generate: {error}", file=sys.stderr)
        return 1
    source_label = DEFAULT_SOURCE if source.startswith(("http://", "https://")) or check else f"{APP_REPOSITORY}:{APP_SPEC_PATH}"
    try:
        outputs = {
            ROOT / "src" / "models.rs": rustfmt(models),
            ROOT / "src" / "operations.rs": rustfmt(operations),
            ROOT / "tests" / "support" / "generated.rs": rustfmt(generator.render_test_support()),
        }
    except GenerateError as error:
        print(f"generate: {error}", file=sys.stderr)
        return 1
    if check:
        stale = [str(p.relative_to(ROOT)) for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            print(f"generate --check: stale {', '.join(stale)}; run python3 scripts/generate.py", file=sys.stderr)
            return 1
        print(f"generate --check: OK ({len(generator.components)} schemas, {count} operations)")
        return 0
    commit = resolve_app_commit(app_commit)
    outputs[ROOT / "src" / "provenance.rs"] = rustfmt(render_provenance(raw, doc, source_label, commit, count))
    (ROOT / "openapi.json").write_bytes(raw)
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(
        f"generated {count} operations and {len(generator.components)} schemas from {source_label} "
        f"(sha256 {hashlib.sha256(raw).hexdigest()}, app commit {commit or 'unknown'})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
