// Code generated by scripts/generate.py from the 0xinsider OpenAPI document. DO NOT EDIT.
//! Which OpenAPI document this release was generated from.
//!
//! Compare [`OPENAPI_SHA256`] with `shasum -a 256` of
//! <https://0xinsider.com/api/v1/openapi.json> to see whether a release is behind the API.

/// Where the document came from: the published URL, or the app repository path when generated from a file.
pub const OPENAPI_SOURCE: &str = "https://0xinsider.com/api/v1/openapi.json";
/// SHA-256 of the document bytes as fetched.
pub const OPENAPI_SHA256: &str = "c69d83281d826457dd3c62bc28626e9c50e4e6e0ff3661a495b70a888ea4f527";
/// The document's `info.version`.
pub const OPENAPI_VERSION: &str = "1.0.0";
/// Operations in the document, including the two read by hand (the stream) or refused (`GET /api/v1/mcp`).
pub const OPERATION_COUNT: usize = 67;
/// The repository that owns the document.
pub const APP_REPOSITORY: &str = "0xinsider/0xinsider";
/// The document's path in that repository.
pub const APP_SPEC_PATH: &str = "web/public/api/v1/openapi.json";
/// The app repository commit that last changed the document, or `None` when it could not be resolved.
pub const APP_COMMIT: Option<&str> = Some("65cf545a67aad01c12f204220ec31e2591d0ea64");
